<a href="https://colab.research.google.com/github/Samarthsaxena071/DATA-ENGG-BASIC-PROJECTS/blob/main/MovieAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import requests

url = f"https://api.themoviedb.org/3/movie/popular?api_key=589d7d8c3bd79bac594a5a7059cfd193"
response = requests.get(url)
data = response.json()
data

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg',
   'genre_ids': [28, 80, 53],
   'id': 1197306,
   'original_language': 'en',
   'original_title': 'A Working Man',
   'overview': "Levon Cade left behind a decorated military career in the black ops to live a simple life working construction. But when his boss's daughter, who is like family to him, is taken by human traffickers, his search to bring her home uncovers a world of corruption far greater than he ever could have imagined.",
   'popularity': 633.0389,
   'poster_path': '/xUkUZ8eOnrOnnJAfusZUqKYZiDu.jpg',
   'release_date': '2025-03-26',
   'title': 'A Working Man',
   'video': False,
   'vote_average': 6.4,
   'vote_count': 484},
  {'adult': False,
   'backdrop_path': '/44YfHklKam8COMUxDZop2Lnp0CS.jpg',
   'genre_ids': [28, 80, 53],
   'id': 668489,
   'original_language': 'en',
   'original_title': 'Havoc',
   'overview': "When a drug heist swerves lethally out of control, a jaded cop fights his way through a corrupt city's criminal underworld to save a politician's son.",
   'popularity': 580.3429,
   'poster_path': '/r46leE6PSzLR3pnVzaxx5Q30yUF.jpg',
   'release_date': '2025-04-24',
   'title': 'Havoc',
   'video': False,
   'vote_average': 6.622,
   'vote_count': 307},
  {'adult': False,
   'backdrop_path': '/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg',
   'genre_ids': [10751, 35, 12, 14],
   'id': 950387,
   'original_language': 'en',
   'original_title': 'A Minecraft Movie',
   'overview': "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
   'popularity': 423.6209,
   'poster_path': '/iPPTGh2OXuIv6d7cwuoPkw8govp.jpg',
   'release_date': '2025-03-31',
   'title': 'A Minecraft Movie',
   'video': False,
   'vote_average': 6.2,
   'vote_count': 755},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [99],
   'id': 1471014,
   'original_language': 'en',
   'original_title': 'Van Gogh by Vincent',
   'overview': 'In a career that lasted only ten years, Vincent Van Gogh painted one subject more than any other: himself. This is the story of Vincent told using eight of his most iconic self-portraits.',
   'popularity': 396.948,
   'poster_path': '/z73X4WKZghBh5fri31o8P6vBEB2.jpg',
   'release_date': '2025-03-26',
   'title': 'Van Gogh by Vincent',
   'video': False,
   'vote_average': 6.125,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/Zes06xI18u47pblwRGTtqRm0R8.jpg',
   'genre_ids': [28, 53, 80, 18],
   'id': 1276073,
   'original_language': 'ja',
   'original_title': '新幹線大爆破',
   'overview': 'When panic erupts on a Tokyo-bound bullet train that will explode if it slows below 100 kph, authorities race against time to save everyone on board.',
   'popularity': 349.9755,
   'poster_path': '/qkTKtOHK9JEEOHgPQZ0dFtzs5ML.jpg',
   'release_date': '2025-04-23',
   'title': 'Bullet Train Explosion',
   'video': False,
   'vote_average': 6.698,
   'vote_count': 96},
  {'adult': False,
   'backdrop_path': '/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg',
   'genre_ids': [28, 14, 12],
   'id': 324544,
   'original_language': 'en',
   'original_title': 'In the Lost Lands',
   'overview': 'A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where she and her guide, the drifter Boyce, must outwit and outfight both man and demon.',
   'popularity': 307.5934,
   'poster_path': '/twy1IVJFgaZWA21Sr6kohEOmdFW.jpg',
   'release_date': '2025-02-27',
   'title': 'In the Lost Lands',
   'video': False,
   'vote_average': 6.326,
   'vote_count': 298},
  {'adult': False,
   'backdrop_path': '/4eC0tsU9OxR3Adlo1yRJYUDraW9.jpg',
   'genre_ids': [28, 53],
   'id': 1092899,
   'original_language': 'en',
   'original_title': 'The Siege',
   'overview': 'International assassin Walker is compromised during a mission and sent to a reassignment center for a new identity. During his stay at the facility, a ruthless assault team storms the compound searching for someone their boss has lost. Walker begrudgingly falls in with skilled hitwoman Elda and her mysterious ward Juliet in order to survive the night.',
   'popularity': 291.2397,
   'poster_path': '/hVh4hMzkXNLnScudbid6hDvjMPk.jpg',
   'release_date': '2023-03-10',
   'title': 'The Siege',
   'video': False,
   'vote_average': 5.456,
   'vote_count': 45},
  {'adult': False,
   'backdrop_path': '/jhL4eTpccoZSVehhcR8DKLSBHZy.jpg',
   'genre_ids': [28, 53, 878],
   'id': 822119,
   'original_language': 'en',
   'original_title': 'Captain America: Brave New World',
   'overview': 'After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.',
   'popularity': 253.9094,
   'poster_path': '/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
   'release_date': '2025-02-12',
   'title': 'Captain America: Brave New World',
   'video': False,
   'vote_average': 6.154,
   'vote_count': 1665},
  {'adult': False,
   'backdrop_path': '/bFmziv84NfEVEGTK8c6EVY3bxve.jpg',
   'genre_ids': [28, 80, 9648, 53],
   'id': 1180906,
   'original_language': 'en',
   'original_title': 'Desert Dawn',
   'overview': 'A newly appointed small-town sheriff and his begrudging deputy get tangled up in a web of lies and corruption involving shady businessmen and the cartel while investigating the murder of a mysterious woman.',
   'popularity': 249.1097,
   'poster_path': '/S21BfLrJSD9njucBfY3CKqp8rD.jpg',
   'release_date': '2025-05-15',
   'title': 'Desert Dawn',
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/oUgVgGaNqV9Y0Zdyjc1kCpzIe4G.jpg',
   'genre_ids': [27, 53],
   'id': 1233413,
   'original_language': 'en',
   'original_title': 'Sinners',
   'overview': 'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.',
   'popularity': 244.6365,
   'poster_path': '/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg',
   'release_date': '2025-04-16',
   'title': 'Sinners',
   'video': False,
   'vote_average': 7.624,
   'vote_count': 444},
  {'adult': False,
   'backdrop_path': '/6dC7ULfiutxwEAs7LjWHL2Tc7Zv.jpg',
   'genre_ids': [27, 35],
   'id': 1124620,
   'original_language': 'en',
   'original_title': 'The Monkey',
   'overview': 'When twin brothers find a mysterious wind-up monkey, a series of outrageous deaths tear their family apart. Twenty-five years later, the monkey begins a new killing spree forcing the estranged brothers to confront the cursed toy.',
   'popularity': 209.1213,
   'poster_path': '/yYa8Onk9ow7ukcnfp2QWVvjWYel.jpg',
   'release_date': '2025-02-14',
   'title': 'The Monkey',
   'video': False,
   'vote_average': 5.872,
   'vote_count': 531},
  {'adult': False,
   'backdrop_path': '/sQa299yggIkxfwKJFgzYwDdsC9t.jpg',
   'genre_ids': [878, 27, 53],
   'id': 931349,
   'original_language': 'en',
   'original_title': 'Ash',
   'overview': 'A woman wakes up on a distant planet and finds the crew of her space station viciously killed. Her investigation into what happened sets in motion a terrifying chain of events.',
   'popularity': 203.835,
   'poster_path': '/5Oz39iyRuztiA8XqCNVDBuy2Ut3.jpg',
   'release_date': '2025-03-20',
   'title': 'Ash',
   'video': False,
   'vote_average': 5.4,
   'vote_count': 135},
  {'adult': False,
   'backdrop_path': '/1YMrOtrW7b4pL2lfD8UciZPOJGs.jpg',
   'genre_ids': [18, 53, 9648],
   'id': 974576,
   'original_language': 'en',
   'original_title': 'Conclave',
   'overview': 'After the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the covert and ancient ritual of electing a new one. Sequestered in the Vatican with the Catholic Church’s most powerful leaders until the process is complete, Lawrence finds himself at the center of a conspiracy that could lead to its downfall.',
   'popularity': 190.1026,
   'poster_path': '/l4WXg5oQPK6GVlISKQNIUGb8rKJ.jpg',
   'release_date': '2024-10-25',
   'title': 'Conclave',
   'video': False,
   'vote_average': 7.21,
   'vote_count': 2159},
  {'adult': False,
   'backdrop_path': '/k32XKMjmXMGeydykD32jfER3BVI.jpg',
   'genre_ids': [28, 9648, 18],
   'id': 1045938,
   'original_language': 'en',
   'original_title': 'G20',
   'overview': 'After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.',
   'popularity': 167.1429,
   'poster_path': '/wv6oWAleCJZUk5htrGg413t3GCy.jpg',
   'release_date': '2025-04-09',
   'title': 'G20',
   'video': False,
   'vote_average': 6.6,
   'vote_count': 403},
  {'adult': False,
   'backdrop_path': '/sNx1A3822kEbqeUxvo5A08o4N7o.jpg',
   'genre_ids': [28, 35, 53],
   'id': 1195506,
   'original_language': 'en',
   'original_title': 'Novocaine',
   'overview': 'When the girl of his dreams is kidnapped, everyman Nate turns his inability to feel pain into an unexpected strength in his fight to get her back.',
   'popularity': 158.3127,
   'poster_path': '/xmMHGz9dVRaMY6rRAlEX4W0Wdhm.jpg',
   'release_date': '2025-03-12',
   'title': 'Novocaine',
   'video': False,
   'vote_average': 6.89,
   'vote_count': 636},
  {'adult': False,
   'backdrop_path': '/kFXtAwJYbRTqiyQpE9kDc8qEP3X.jpg',
   'genre_ids': [28, 53],
   'id': 1225915,
   'original_language': 'hi',
   'original_title': 'ज्वेल थीफ: द हीस्ट बिगिन्स',
   'overview': 'In this high-octane battle of wits and wills, ingenious con artist Rehan devises a diamond heist while trying to outsmart Rajan, his sadistic adversary.',
   'popularity': 155.5858,
   'poster_path': '/eujLbO0kf1eqWC8XpHUJdtAVW2J.jpg',
   'release_date': '2025-04-25',
   'title': 'Jewel Thief: The Heist Begins',
   'video': False,
   'vote_average': 6.6,
   'vote_count': 14},
  {'adult': False,
   'backdrop_path': '/r4X2xRrWleVgx0kahP27xRmm3ia.jpg',
   'genre_ids': [27, 53],
   'id': 1083968,
   'original_language': 'en',
   'original_title': 'Locked',
   'overview': 'When Eddie breaks into a luxury SUV, he steps into a deadly trap set by William, a self-proclaimed vigilante delivering his own brand of twisted justice. With no means of escape, Eddie must fight to survive in a ride where escape is an illusion, survival is a nightmare, and justice shifts into high gear.',
   'popularity': 152.2937,
   'poster_path': '/hhkiqXpfpufwxVrdSftzeKIANl3.jpg',
   'release_date': '2025-03-20',
   'title': 'Locked',
   'video': False,
   'vote_average': 6.1,
   'vote_count': 87},
  {'adult': False,
   'backdrop_path': '/ddIkmH3TpR6XSc47jj0BrGK5Rbz.jpg',
   'genre_ids': [10752, 28, 18],
   'id': 374720,
   'original_language': 'en',
   'original_title': 'Dunkirk',
   'overview': 'The story of the miraculous evacuation of Allied soldiers from Belgium, Britain, Canada and France, who were cut off and surrounded by the German army from the beaches and harbour of Dunkirk between May 26th and June 4th 1940 during World War II.',
   'popularity': 140.7175,
   'poster_path': '/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg',
   'release_date': '2017-07-19',
   'title': 'Dunkirk',
   'video': False,
   'vote_average': 7.45,
   'vote_count': 16752},
  {'adult': False,
   'backdrop_path': '/bMdSmfI0qwpAkvhAL7sqpjmwgf4.jpg',
   'genre_ids': [878, 18],
   'id': 335984,
   'original_language': 'en',
   'original_title': 'Blade Runner 2049',
   'overview': "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
   'popularity': 138.2086,
   'poster_path': '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
   'release_date': '2017-10-04',
   'title': 'Blade Runner 2049',
   'video': False,
   'vote_average': 7.578,
   'vote_count': 14069},
  {'adult': False,
   'backdrop_path': '/hdHIjZxq3SWFqpAz4NFhdbud0iz.jpg',
   'genre_ids': [27, 878],
   'id': 348,
   'original_language': 'en',
   'original_title': 'Alien',
   'overview': 'During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.',
   'popularity': 135.2474,
   'poster_path': '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
   'release_date': '1979-05-25',
   'title': 'Alien',
   'video': False,
   'vote_average': 8.163,
   'vote_count': 15233}],
 'total_pages': 50005,
 'total_results': 1000097}

In [24]:
import pandas as pd

movies = pd.DataFrame(data["results"])
movies['release_date'] = pd.to_datetime(movies['release_date'], errors='coerce')

In [25]:
movies.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/fTrQsdMS2MUw00RnzH0r3JWHhts.jpg,"[28, 80, 53]",1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,/xUkUZ8eOnrOnnJAfusZUqKYZiDu.jpg,2025-03-26,A Working Man,False,6.400,484
1,False,/44YfHklKam8COMUxDZop2Lnp0CS.jpg,"[28, 80, 53]",668489,en,Havoc,When a drug heist swerves lethally out of cont...,580.3429,/r46leE6PSzLR3pnVzaxx5Q30yUF.jpg,2025-04-24,Havoc,False,6.622,307
2,False,/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg,"[10751, 35, 12, 14]",950387,en,A Minecraft Movie,Four misfits find themselves struggling with o...,423.6209,/iPPTGh2OXuIv6d7cwuoPkw8govp.jpg,2025-03-31,A Minecraft Movie,False,6.200,755
3,False,None,[99],1471014,en,Van Gogh by Vincent,"In a career that lasted only ten years, Vincen...",396.9480,/z73X4WKZghBh5fri31o8P6vBEB2.jpg,2025-03-26,Van Gogh by Vincent,False,6.125,4
4,False,/Zes06xI18u47pblwRGTtqRm0R8.jpg,"[28, 53, 80, 18]",1276073,ja,新幹線大爆破,When panic erupts on a Tokyo-bound bullet trai...,349.9755,/qkTKtOHK9JEEOHgPQZ0dFtzs5ML.jpg,2025-04-23,Bullet Train Explosion,False,6.698,96

In [26]:
movies.columns  # columns of movies

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [27]:
movies.isnull().sum()  #tells about the null values in the data

adult                0
backdrop_path        1
genre_ids            0
id                   0
original_language    0
original_title       0
overview             0
popularity           0
poster_path          0
release_date         0
title                0
video                0
vote_average         0
vote_count           0
dtype: int64

In [28]:
movies = movies.dropna(subset=['backdrop_path']) #drop that particular null value

In [29]:
movies.isnull().sum()

adult                0
backdrop_path        0
genre_ids            0
id                   0
original_language    0
original_title       0
overview             0
popularity           0
poster_path          0
release_date         0
title                0
video                0
vote_average         0
vote_count           0
dtype: int64

In [30]:
movies = movies.drop(columns=['adult', 'backdrop_path', 'poster_path', 'video'])

In [31]:
movies.head()

,genre_ids,id,original_language,original_title,overview,popularity,release_date,title,vote_average,vote_count
0,"[28, 80, 53]",1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
1,"[28, 80, 53]",668489,en,Havoc,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307
2,"[10751, 35, 12, 14]",950387,en,A Minecraft Movie,Four misfits find themselves struggling with o...,423.6209,2025-03-31,A Minecraft Movie,6.200,755
4,"[28, 53, 80, 18]",1276073,ja,新幹線大爆破,When panic erupts on a Tokyo-bound bullet trai...,349.9755,2025-04-23,Bullet Train Explosion,6.698,96
5,"[28, 14, 12]",324544,en,In the Lost Lands,A queen sends the powerful and feared sorceres...,307.5934,2025-02-27,In the Lost Lands,6.326,298

In [32]:
#AS WE CAN SEE NOW, GENRE_ID CONSISTS OF MULTIPLE VALUES  SUCH AS [12,18], we need to seperate it for relational database
movies = movies.explode('genre_ids')

In [33]:
movies = movies.rename(columns={
    'id': 'movie_id',
    'title': 'movie_title',
    'vote_average': 'avg_rating'
})
movies.head()

,genre_ids,movie_id,original_language,original_title,overview,popularity,release_date,movie_title,avg_rating,vote_count
0,28,1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
0,80,1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
0,53,1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
1,28,668489,en,Havoc,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307
1,80,668489,en,Havoc,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307

In [34]:
# 1. Create the 'movies' table
movies_table = movies.drop(columns=['genre_ids']).drop_duplicates(subset=['movie_id'])

# 2. Create the 'movie_genres' mapping table
movie_genres_table = movies[['movie_id', 'genre_ids']].rename(columns={'genre_ids': 'genre_id'})

# Check the first few rows
print("Movies Table:")
print(movies_table.head())

print("\nMovie Genres Table:")
print(movie_genres_table.head())

Movies Table:
   movie_id original_language     original_title  \
0   1197306                en      A Working Man
1    668489                en              Havoc
2    950387                en  A Minecraft Movie
4   1276073                ja             新幹線大爆破
5    324544                en  In the Lost Lands

                                            overview  popularity release_date  \
0  Levon Cade left behind a decorated military ca...    633.0389   2025-03-26
1  When a drug heist swerves lethally out of cont...    580.3429   2025-04-24
2  Four misfits find themselves struggling with o...    423.6209   2025-03-31
4  When panic erupts on a Tokyo-bound bullet trai...    349.9755   2025-04-23
5  A queen sends the powerful and feared sorceres...    307.5934   2025-02-27

              movie_title  avg_rating  vote_count
0           A Working Man       6.400         484
1                   Havoc       6.622         307
2       A Minecraft Movie       6.200         755
4  Bullet Train Explosion       6.698          96
5       In the Lost Lands       6.326         298

Movie Genres Table:
   movie_id genre_id
0   1197306       28
0   1197306       80
0   1197306       53
1    668489       28
1    668489       80

In [35]:
movies_table.head()

,movie_id,original_language,original_title,overview,popularity,release_date,movie_title,avg_rating,vote_count
0,1197306,en,A Working Man,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
1,668489,en,Havoc,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307
2,950387,en,A Minecraft Movie,Four misfits find themselves struggling with o...,423.6209,2025-03-31,A Minecraft Movie,6.200,755
4,1276073,ja,新幹線大爆破,When panic erupts on a Tokyo-bound bullet trai...,349.9755,2025-04-23,Bullet Train Explosion,6.698,96
5,324544,en,In the Lost Lands,A queen sends the powerful and feared sorceres...,307.5934,2025-02-27,In the Lost Lands,6.326,298

In [36]:
movies_table = movies_table.drop(columns=['original_title'])

In [38]:
movies_table.head()

,movie_id,original_language,overview,popularity,release_date,movie_title,avg_rating,vote_count
0,1197306,en,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
1,668489,en,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307
2,950387,en,Four misfits find themselves struggling with o...,423.6209,2025-03-31,A Minecraft Movie,6.200,755
4,1276073,ja,When panic erupts on a Tokyo-bound bullet trai...,349.9755,2025-04-23,Bullet Train Explosion,6.698,96
5,324544,en,A queen sends the powerful and feared sorceres...,307.5934,2025-02-27,In the Lost Lands,6.326,298

In [39]:
#TO LOAD MOVIES TABLE INTO DATABASE
!pip install sqlalchemy
!pip install pandas

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.11/dist-packages (2.0.40)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (3.2.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy) (4.13.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [40]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('sqlite:///movies.db')
movies_table.to_sql('movies', engine, if_exists='replace', index=False)
movie_genres_table.to_sql('movie_genres', engine, if_exists='replace', index=False)

53

In [41]:
# Read movies table
movies_from_db = pd.read_sql('SELECT * FROM movies', engine)
movies_from_db.head()

,movie_id,original_language,overview,popularity,release_date,movie_title,avg_rating,vote_count
0,1197306,en,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26 00:00:00.000000,A Working Man,6.400,484
1,668489,en,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24 00:00:00.000000,Havoc,6.622,307
2,950387,en,Four misfits find themselves struggling with o...,423.6209,2025-03-31 00:00:00.000000,A Minecraft Movie,6.200,755
3,1276073,ja,When panic erupts on a Tokyo-bound bullet trai...,349.9755,2025-04-23 00:00:00.000000,Bullet Train Explosion,6.698,96
4,324544,en,A queen sends the powerful and feared sorceres...,307.5934,2025-02-27 00:00:00.000000,In the Lost Lands,6.326,298

In [42]:
# Read movie_genres table
movie_genres_from_db = pd.read_sql('SELECT * FROM movie_genres', engine)
movie_genres_from_db.head()

   movie_id  genre_id
0   1197306        28
1   1197306        80
2   1197306        53
3    668489        28
4    668489        80

In [44]:
#FIND TOP 10 MOST POPULAR MOVIES
query = """
SELECT movie_title, popularity
FROM movies
ORDER BY popularity DESC
LIMIT 10;
"""

top_10_popular = pd.read_sql(query, engine)
top_10_popular

                        movie_title  popularity
0                     A Working Man    633.0389
1                             Havoc    580.3429
2                 A Minecraft Movie    423.6209
3            Bullet Train Explosion    349.9755
4                 In the Lost Lands    307.5934
5                         The Siege    291.2397
6  Captain America: Brave New World    253.9094
7                       Desert Dawn    249.1097
8                           Sinners    244.6365
9                        The Monkey    209.1213

from matplotlib import pyplot as plt
top_10_popular['popularity'].plot(kind='hist', bins=20, title='popularity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
top_10_popular['popularity'].plot(kind='line', figsize=(8, 4), title='popularity')
plt.gca().spines[['top', 'right']].set_visible(False)

In [45]:
movies_table.head()

,movie_id,original_language,overview,popularity,release_date,movie_title,avg_rating,vote_count
0,1197306,en,Levon Cade left behind a decorated military ca...,633.0389,2025-03-26,A Working Man,6.400,484
1,668489,en,When a drug heist swerves lethally out of cont...,580.3429,2025-04-24,Havoc,6.622,307
2,950387,en,Four misfits find themselves struggling with o...,423.6209,2025-03-31,A Minecraft Movie,6.200,755
4,1276073,ja,When panic erupts on a Tokyo-bound bullet trai...,349.9755,2025-04-23,Bullet Train Explosion,6.698,96
5,324544,en,A queen sends the powerful and feared sorceres...,307.5934,2025-02-27,In the Lost Lands,6.326,298

In [46]:
movie_genres_table.head()

   movie_id genre_id
0   1197306       28
0   1197306       80
0   1197306       53
1    668489       28
1    668489       80

In [51]:
#Find Average Rating by Language
query = """
SELECT original_language, AVG(avg_rating) AS avg_rating
FROM movies
GROUP BY original_language;
"""

avg_rating_by_language = pd.read_sql(query, engine)
avg_rating_by_language

  original_language  avg_rating
0                en    6.237941
1                hi    6.600000
2                ja    6.698000

In [52]:
query='''
SELECT STRFTIME('%Y',release_date) AS release_year,COUNT(*) AS movies_count
FROM movies
GROUP BY release_year
ORDER BY release_year;
'''

movies_per_year = pd.read_sql(query,engine)
movies_per_year

  release_year  movies_count
0         1979             1
1         2017             2
2         2023             1
3         2024             1
4         2025            14

In [54]:
#GET ALL MOVIES ALONG WITH THEIR GENRE_ID
query = '''
SELECT m.movie_title,mg.genre_id
FROM movies m
JOIN movie_genres mg
ON m.movie_id = mg.movie_id;
'''

movies_with_genre = pd.read_sql(query,engine)
movies_with_genre

                         movie_title  genre_id
0                      A Working Man        28
1                      A Working Man        53
2                      A Working Man        80
3                              Havoc        28
4                              Havoc        53
5                              Havoc        80
6                  A Minecraft Movie        12
7                  A Minecraft Movie        14
8                  A Minecraft Movie        35
9                  A Minecraft Movie     10751
10            Bullet Train Explosion        18
11            Bullet Train Explosion        28
12            Bullet Train Explosion        53
13            Bullet Train Explosion        80
14                 In the Lost Lands        12
15                 In the Lost Lands        14
16                 In the Lost Lands        28
17                         The Siege        28
18                         The Siege        53
19  Captain America: Brave New World        28
20  Captain America: Brave New World        53
21  Captain America: Brave New World       878
22                       Desert Dawn        28
23                       Desert Dawn        53
24                       Desert Dawn        80
25                       Desert Dawn      9648
26                           Sinners        27
27                           Sinners        53
28                        The Monkey        27
29                        The Monkey        35
30                               Ash        27
31                               Ash        53
32                               Ash       878
33                          Conclave        18
34                          Conclave        53
35                          Conclave      9648
36                               G20        18
37                               G20        28
38                               G20      9648
39                         Novocaine        28
40                         Novocaine        35
41                         Novocaine        53
42     Jewel Thief: The Heist Begins        28
43     Jewel Thief: The Heist Begins        53
44                            Locked        27
45                            Locked        53
46                           Dunkirk        18
47                           Dunkirk        28
48                           Dunkirk     10752
49                 Blade Runner 2049        18
50                 Blade Runner 2049       878
51                             Alien        27
52                             Alien       878

from matplotlib import pyplot as plt
movies_with_genre['genre_id'].plot(kind='hist', bins=20, title='genre_id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
movies_with_genre['genre_id'].plot(kind='line', figsize=(8, 4), title='genre_id')
plt.gca().spines[['top', 'right']].set_visible(False)

In [55]:
#TO CONCAT ALL THE GENRE ID TO A SPECIFIC MOVIE
query='''
SELECT m.movie_title,GROUP_CONCAT(mg.genre_id) as genre_ids
from movies m
JOIN movie_genres mg
ON m.movie_id = mg.movie_id
GROUP BY movie_title;
'''

movies_with_genre = pd.read_sql(query,engine)
movies_with_genre

                         movie_title       genre_ids
0                  A Minecraft Movie  12,14,35,10751
1                      A Working Man        28,53,80
2                              Alien          27,878
3                                Ash       27,53,878
4                  Blade Runner 2049          18,878
5             Bullet Train Explosion     18,28,53,80
6   Captain America: Brave New World       28,53,878
7                           Conclave      18,53,9648
8                        Desert Dawn   28,53,80,9648
9                            Dunkirk     18,28,10752
10                               G20      18,28,9648
11                             Havoc        28,53,80
12                 In the Lost Lands        12,14,28
13     Jewel Thief: The Heist Begins           28,53
14                            Locked           27,53
15                         Novocaine        28,35,53
16                           Sinners           27,53
17                        The Monkey           27,35
18                         The Siege           28,53